### ISSUE TITLE
Add a check for https://securityscorecards.dev

### ISSUE THREAD

**Issue by caniszczyk** [cncf/clomonitor#1015]
We should check if a project is using https://securityscorecards.dev

We should think about how to check for it though... maybe look for a GHA?

**Comment by tegioz** [comment]
I would suggest checking for the presence of the [Scorecard badge](https://github.com/marketplace/actions/ossf-scorecard-action#scorecard-badge) in the README file. That way we are also encouraging projects to publish their results ([which helps the Scorecard project scale](https://github.com/marketplace/actions/ossf-scorecard-action#publishing-results)) and spread the word about Scorecard.

**Comment by tegioz** [comment]
Deployed!

<img width="1200" alt="scorecard_badge" src="https://user-images.githubusercontent.com/1213902/236138810-c17d92fc-d160-456c-b3c3-ce01395cbcbc.png">

<img width="1200" alt="scorecard_badge_stats" src="https://user-images.githubusercontent.com/1213902/236138823-0f649070-f173-4344-bd5f-6307aa0318b5.png">
