### ISSUE TITLE
Annual report automation

### ISSUE THREAD

**Issue by jeefy** [cncf/clomonitor#1093]
Looking for a check to see if the project is up to date regarding annual reports.

This check would be special in the sense that it will take action when the check is not passing: it'll file an issue on the corresponding repo (community or main code) as well as periodic reminders (every 30d) in the form of comments.

Things TBD (cc @amye to fill in)
- Template Title/Body of the issue to be created
- Timing -- Do we globally state "June 1st is the start of a new annual review cycle" or do we look at the age of the previous-year's annual report and once it's >1yr old, trigger?
- Do we automatically close the tracking issue once we detect a merged project review (or PR submission?)
- Anything else we're missing?

**Comment by amye** [comment]
This is pretty easy! 
(1) Link into https://github.com/cncf/toc/blob/main/process/sandbox-annual-review.md as the template
(2) You look at when the project entered CNCF, the annual review is due two months after that date -- hopefully that data is all in the landscape! https://github.com/cncf/toc/blob/main/docs/projects.md has this but we're trying to move all of that into the landscape.
(3) Yes? Can we think of a reason why we wouldn't?

**Comment by tegioz** [comment]
Hi!

We've split this task in two phases:

1. Add the annual review check
2. Notify projects when the check is not passing

**(1) is already complete!** (#1101) By using a [combination of filters](https://clomonitor.io/search?foundation=cncf&maturity=sandbox&not_passing_check=annual_review&accepted_to=2022-03-22&page=1) it's now easy to spot the projects that are not passing this check. You can see it in action in [CLOMonitor](https://clomonitor.io/search?foundation=cncf&maturity=sandbox&not_passing_check=annual_review&accepted_to=2022-03-22&page=1).

Some details about how it works at the moment:

- The check relies on the `annual_review_url` and `annual_review_date` fields in the `extra` section of the *landscape.yml* file, so it's important that this information is up to date.

```yaml
extra:
    annual_review_url: https://github.com/cncf/toc/pull/993
    annual_review_date: '2023-01-12'
```

- The check has been added to the `documentation` section and it's part of the `community` check set. The annual review PR url is accessible from the check when available.

<img width="1226" alt="Screenshot 2023-05-22 at 13 26 47" src="https://github.com/cncf/clomonitor/assets/1213902/53fbd33e-f168-45cd-896a-d3cddc586727">

- Only CNCF Sandbox projects are expected to pass this check. Other projects are exempt (this is highlighted on the UI).

<img width="1226" alt="Screenshot 2023-05-22 at 13 27 59" src="https://github.com/cncf/clomonitor/assets/1213902/c22eee37-1f15-4c51-a451-766b4804d26d">

- CNCF Sandbox projects are exempt to pass this check in the first year (+ 2 months grace period) after they were accepted.

<img width="1226" alt="Screenshot 2023-05-22 at 13 29 10" src="https://github.com/cncf/clomonitor/assets/1213902/f5e939e0-e8d5-4784-82ab-f078a5e33cf7">

- When a project has already presented an annual review, it's expected that they present another one 1 year (+ 2 months grace period) after the last one. The reason we've done it this way is that, if we were always making decisions based on the accepted date + 2 months, if a project presents an annual review 10 months after the due date, we'd be requiring another one just 2 months after the last one, which would be annoying.

<img width="1226" alt="Screenshot 2023-05-22 at 13 31 00" src="https://github.com/cncf/clomonitor/assets/1213902/002efdbc-fd76-48d8-a6f7-7ebd1c66c710">

Next we'll focus on the notifications part. It'd be great if the annual reviews information in the landscape was up to date before we have it ready, to avoid notifying projects that have the annual review up to date 🙂

**Comment by tegioz** [comment]
Sample notifications content:

(@amye @jeefy please let us know your thoughts *-i.e. would you like someone to be tagged on those issues?-*)

## Annual review due

**Sandbox** projects are subject to an *annual review* by the **TOC**. This is intended to be a lightweight process to ensure that projects are on track, and getting the support they need.

[CLOMonitor](https://clomonitor.io) has detected that the annual review for this project has not been filed yet. CLOMonitor relies on the information in the `annual_review_url` and `annual_review_date` fields in the [CNCF Landscape configuration file](https://github.com/cncf/landscape/blob/master/landscape.yml) for this check. If your annual review has already been presented, please make sure this information has been correctly added.

For more information about how to file your annual review please see the [Sandbox annual review documentation](https://github.com/cncf/toc/blob/main/process/sandbox-annual-review.md#how-to-file-your-annual-review).

## Annual review due reminder

This is a friendly reminder to let you know that your annual review is still due.

For more information about how to file your annual review please see the [Sandbox annual review documentation](https://github.com/cncf/toc/blob/main/process/sandbox-annual-review.md#how-to-file-your-annual-review).

**Comment by tegioz** [comment]
Done in #1101 and #1102!

We'll deploy it on Monday. If you'd like to update the templates or have any question please let us know 🙂
