### ISSUE TITLE
Issue parsing landscape.yaml is affecting scores

### ISSUE THREAD

**Issue by aaguiarz** [cncf/clomonitor#1181]
Hi! 

All projects now have warnings like this, which slightly decreases their score:

<img width="662" alt="image" src="https://github.com/cncf/clomonitor/assets/1636576/1c7f8000-4805-433d-9f73-997e574a28ad">

**Comment by tegioz** [comment]
Thanks for reporting this @aaguiarz! We'll fix it very soon 🙂
