### ISSUE TITLE
Does CLOMonitor/CLOTributor follow redirects?

### ISSUE THREAD

**Issue by aliok** [cncf/clomonitor#1205]
This is not an issue right now, but more of a question.

We had a GH org called `knative-sandbox` which is now renamed to `knative-extension`.

https://github.com/knative-sandbox/eventing-kafka-broker/ redirects to https://github.com/knative-extensions/eventing-kafka-broker automatically on browser.

Not sure how that is in terms of GH API access.

We would like to update the data file in CLOMonitor anyway, but I was curious about this.

Related: https://github.com/knative/community/issues/1415

**Comment by tegioz** [comment]
Hi @aliok 👋

Yes, both CLOMonitor and CLOTributor should follow GitHub repositories redirects 🙂
