### ISSUE TITLE
Remove analytics

### ISSUE THREAD

**Issue by ghost** [cncf/clomonitor#1307]
Please remove the embedding of analytics in the project website as a best practice as it is contrary to user privacy and requires a GDPR consent dialog (cookie banner) on the same website, which degrades the user experience. As a high profile example, GitHub has removed [all tracking cookies](https://github.blog/2020-12-17-no-cookie-for-you/) in 2020 for a better user experience.

**Comment by tegioz** [comment]
Thanks @janosdebugs, we'll take care of this soon 🙂
