### ISSUE TITLE
"Summary Table" check and clomonitor_name field: doc update proposal

### ISSUE THREAD

**Issue by yada** [cncf/clomonitor#1519]
Hi,

To pass the "Summary Table" check the [CNCF landscape.yml file](https://github.com/cncf/landscape/blob/master/landscape.yml) must contain at least one of the [summary_* fields](https://github.com/cncf/landscape/blob/master/docs/item_summary.md) in the project’s extra section. As stated in the doc: https://clomonitor.io/docs/topics/checks/#summary-table

However, the clomonitor_name field is mandatory to map entries in the landscape to the CLOMonitor data files. Without it, checks based on the landscape cannot be performed. But this point is not written in the [doc](https://clomonitor.io/docs/topics/checks/#summary-table) above.

I propose to create a PR to update the documentation accordingly:

Mandatory
> extra:
  clomonitor_name: project-name
  
Regards,
Yacine

**Comment by yada** [comment]
@tegioz ok for you?
BTW, do you think that the clomonitor_name field also needs to be added here: https://github.com/cncf/landscape/blob/master/docs/item_summary.md ? with a comment "mandatory for clomonitor check"?

**Comment by tegioz** [comment]
Hi @yada

Thanks, that sounds good to me 👍

It'd be good to mention that the `project-name` used in the `clomonitor_name` field *must* match exactly the project's name used in the corresponding CLOMonitor data file.

Regarding the update to the `item_summary` document in the landscape repo, I think it'd be best to leave it as it is for now. The summary can be used by any landscape item, but not all items are listed on CLOMonitor (only CNCF projects), so it could get confusing.

Please note that this field is also documented briefly [here](https://github.com/cncf/landscape2/blob/e45368319bf44b5894039f6b49c6468bdff67112/docs/config/data.yml#L140-L144) (the part of how CLOMonitor relies on that field for other purposes was intentionally omitted).
