### ISSUE TITLE
Add additional containerd repos

### ISSUE THREAD

**Issue by jeefy** [cncf/clomonitor#160]
https://github.com/containerd/project -- Governance repo, has their Security/Governance info
https://github.com/containerd/containerd.io -- Their website and docs repo

Edit: Feel free to assign this to me :) Happy to PR it in later.

**Comment by tegioz** [comment]
Hi @jeefy

Could you please instead open a PR (or an issue) in their main repository to edit the [Project details](https://github.com/containerd/containerd#project-details) section in their `README` file to include 3 minimal subsections (`contributing`, `governance` and `maintainers`) that point to the corresponding files in their project repo? They already have the information there, which is great for discoverability, it's just that at the moment they have it in a format that we cannot detect yet. So it'll be just a minor update. They could also use a `.github` repo at the org level for some of the [Community Health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file), which we also support.

IMHO this is the best way to handle this at the moment, and we should encourage and help projects to get there. We've tried to help some make CLOMonitor happy this way successfully, like [Kubernetes](https://github.com/kubernetes/kubernetes/pull/108110), [KEDA](https://github.com/kedacore/keda/pull/2704) and [Cilium](https://github.com/cilium/cilium/pull/19037). If you could help us with that it'd be great 🙂 I think in this first stage we should focus on getting the most out of primary repositories and complement the missing parts with pointers in the README file.

Thanks!

**Comment by tegioz** [comment]
Thanks to the improvements done in #162 all [containerd documentation checks are now passing](https://clomonitor.io/projects/containerd/containerd). So no need to create the suggested PR in their repository to update the README file or add more repositories to CLOMonitor.

Please let's try to encourage and help projects to include headers (or links in the supported format) in their README file pointing to relevant documents when needed. Thanks! 🙂
