### ISSUE TITLE
bug: security policy check does not find /SECURITY.md in KubeStellar repo

### ISSUE THREAD

**Issue by clubanderson** [cncf/clomonitor#1633]
Per the security policy section in clomonitor, our repo has "SECURITY.md" in the root of the main branch of our repo kubestellar/kubestellar. However, clomonitor flags the file as missing.

SECURITY POLICY:
ID: security_policy

Clearly documented security processes explaining how to report security issues to the project.

This check passes if:

A security policy file is found in the repository. Globs used:
"security*"
".github/security*"
"docs/security*"

CASE SENSITIVE: false
A security policy reference is found in the repository’s README file. This can be in the form of a title header or a link. Regexps used:
"(?im)^#+.*security.*$"
"(?im)^security$"
"(?i)\[.*security.*\]\(.*\)"
A security policy file is found in Github (in the [.github default community health files repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file), for example).

**Comment by tegioz** [comment]
Hi @clubanderson 👋

From: <https://clomonitor.io/projects/cncf/kubestellar#kubestellar_security>

That check seems to be passing and the link points to the `SECURITY.md` file in the `KubeStellar` repo.

![Image](https://github.com/user-attachments/assets/806029b8-5210-4485-b065-953947678c52)

**Comment by clubanderson** [comment]
Thank you - I will close
