### ISSUE TITLE
trademark text is at bottom of kubestellar.io but not found by clomonitor

### ISSUE THREAD

**Issue by clubanderson** [cncf/clomonitor#1635]
KubeStellar.io has the required text to match the clomonitor for "trademark" - clomonitor is not recognizing this. please exempt or advise.

![Image](https://github.com/user-attachments/assets/751ab635-dce5-4063-9ee1-c69e854d9203)

**Comment by tegioz** [comment]
Hi @clubanderson 👋 

The reason why CLOMonitor can't find it is the kind of redirection used (`<meta http-equiv="refresh" ...>`), which isn't supported. An exemption is the best way to go in this case.

Exemptions need to be declared in your repository, please [check out the docs for more details](https://clomonitor.io/docs/topics/checks/#exemptions). Note that the information declared in the exemption will be displayed in CLOMonitor's UI.

**Comment by clubanderson** [comment]
ok, I just put the .clomonitor.yml into source and it has merged. Can you check on your end if it is being processed correctly?

**Comment by tegioz** [comment]
Awesome, no worries!
