### ISSUE TITLE
Show timestamp of latest check, per project

### ISSUE THREAD

**Issue by chalin** [cncf/clomonitor#176]
It would be useful to know when a particular project was last checked, especially given that there are different re-check rates for projects -- as I understand it from [checks.md](https://github.com/cncf/clomonitor/blob/main/docs/checks.md):

> These checks are run *every hour*, provided the repository has changed since the last time it was checked. In the case of repositories that don't change often, we make sure that they are checked at least *once a day* anyway. 

/cc @nate-double-u

**Comment by tegioz** [comment]
Hi @chalin

We are displaying it in the search results page, we'll add it to the project's page as well 👍 (I'd swear it was there too, we must have removed it at some point while updating the design 😅).

<img width="1490" alt="Screen Shot 2022-03-15 at 14 16 17" src="https://user-images.githubusercontent.com/1213902/158385955-509b2bbb-cb27-4ff7-91fa-d530a6f6168e.png">
