### ISSUE TITLE
Add a way to specific a different location for info

### ISSUE THREAD

**Issue by duglin** [cncf/clomonitor#183]
e.g. our roadmap isn't at the root of the repo, it's in "community". It would be nice if there was a way to tell the tool to look some place else. Perhaps via a .clomonitor file? I do think that it would be good to have the tool check to see if the main README included a pointer to the file regardless of where the file lives.

**Comment by tegioz** [comment]
Hi @duglin 👋 

You can add a reference to the README file pointing to a `roadmap` file in another repo, that's already supported 🙂

This can be done in two different ways:

- Adding a title header that contains `roadmap` (any level would work, #, ##, etc). You can see an example [here](https://github.com/kubernetes/kubernetes#roadmap).
- Adding a markdown link named `roadmap`.

For more details please see the [checks reference](https://github.com/cncf/clomonitor/blob/main/docs/checks.md).

Hope this helps.-

**Comment by duglin** [comment]
@tegioz thanks!!

**Comment by tegioz** [comment]
No worries 👍

**Comment by duglin** [comment]
One more question... how often does the tool run? Is there a way to force it to run so I can check things immediately?

**Comment by tegioz** [comment]
It runs every hour provided something has changed in the repo. Otherwise at least once a day. But you can run it locally to check immediately. Please see #20 for more details 🙂
