### ISSUE TITLE
Issues with Kubernetes clomonitor page 

### ISSUE THREAD

**Issue by dims** [cncf/clomonitor#196]
Looking at https://clomonitor.io/projects/kubernetes/kubernetes

- Artifact Hub badge
  - Not sure what category we would fall into :)
- Developer Certificate of Origin
  - we use CLA instead of DCO so we should not be penalized for this right?
-  Slack presence
  - fun message here - "Projects should have presence in the CNCF Slack or Kubernetes Slack" ?

**Comment by tegioz** [comment]
Hi @dims 👋

Yesterday we released a feature that should be helpful with some of these issues, [checks exemptions](https://github.com/cncf/clomonitor/blob/main/docs/checks.md#exemptions). Actually, your first point appears in the doc as an example! 😀

If you end up setting up a .clomonitor.yml file for the exemptions, maybe the license scanning section can also be of interest to you to fix that check as well 😉

Hope this helps.-

**Comment by tegioz** [comment]
The Artifact Hub badge and DCO checks should probably be declared as exemptions, but maybe a link to the Kubernetes Slack could be added to the [support section of the README file](https://github.com/kubernetes/kubernetes#support).

**Comment by tegioz** [comment]
We've just added a check for `CLA`. When this check passes, the `DCO` check is marked as exempt automatically, so you don't need to handle this exception manually anymore.

<img width="1310" alt="cla-dco" src="https://user-images.githubusercontent.com/1213902/161750883-1a4afbd0-0ea1-4746-8740-811a981a3a1c.png">

**Comment by tegioz** [comment]
Hi @bentheelder 👋

I just stumbled across <https://twitter.com/bentheelder/status/1555233342798249984> by coincidence 🙂 @dims raised some issues with the Kubernetes CLOMonitor page in this issue some time ago. If you find anything else that doesn't seem right, please don't hesitate pinging us.

Regarding the Slack check, at the moment we check that a link to the project's Slack is present in the README file (more details [here](https://clomonitor.io/docs/topics/checks/#slack-presence)), so it'd be great if a link could be added to the [support section of the README file](https://github.com/kubernetes/kubernetes#support) as discussed above ([some changes were already made a few months ago](https://github.com/kubernetes/kubernetes/pull/108110) to the README file to make CLOMonitor happy).

Alternatively, [an exemption could be declared by using the CLOMonitor metadata file](https://clomonitor.io/docs/topics/checks/#exemptions), which would also help for other checks that don't apply to the Kubernetes project, like the Artifact Hub badge.

Thanks!

/cc @caniszczyk
