### ISSUE TITLE
Disable some checks for non-source code repos

### ISSUE THREAD

**Issue by duglin** [cncf/clomonitor#209]
Is there a way to disable to license scanning part of this since our repo doesn't have source code?

**Comment by duglin** [comment]
Same question for Artifact Hub badge

**Comment by tegioz** [comment]
Hi @duglin 👋 

We are considering supporting additional repository kinds instead of just primary and secondary (i.e. docs repositories, etc, please see #151 for more details). Please stay tuned, we'll keep you posted 🙂 

Closing in favor of #151
