### ISSUE TITLE
Keda should include the website/docs repo

### ISSUE THREAD

**Issue by chalin** [cncf/clomonitor#216]
Currently, the [Keda] page only lists:

- https://github.com/kedacore/keda

It should also include:

- https://github.com/kedacore/keda-docs

and maybe also:

- https://github.com/kedacore/governance

[Keda]: https://clomonitor.io/projects/keda/keda

**Comment by jeffhollan** [comment]
Will open a PR for this - thanks for the heads up @chalin

**Comment by chalin** [comment]
Thanks @jeffhollan. Pls me on the PR.

**Comment by tegioz** [comment]
Hi @chalin @jeffhollan 👋 

Adding the `docs` repo sounds good. However, I wouldn't recommend adding the governance repo to run the `community` checks on it. That repo doesn't contain some of the information we look for in that check set, so fewer checks will pass and the project's score will be worse (when it shouldn't, as it is really passing almost all checks).

@tomkerkhove from the KEDA team [made some adjustments recently](https://github.com/kedacore/keda/commit/e242720d4aa9ed8d3ff275ad18e6d50d5e05afa2) to make CLOMonitor happy in a way that makes the information more discoverable by users from the main project's repo, which IMHO is great and the best way to proceed.

**Comment by tomkerkhove** [comment]
I think the goal of CloMonitor is to help with discoverability for end-users and contributors so it makes sense to pull info from main repo and optionally docs, but I can see why Governance can be left out and main repo should point to it.

**Comment by jeffhollan** [comment]
@tegioz sounds good - updated PR to only include docs repo

**Comment by tegioz** [comment]
Thanks @jeffhollan 👍
