### ISSUE TITLE
Create a clomonitor instance for LFAI

### ISSUE THREAD

**Issue by caniszczyk** [cncf/clomonitor#221]
I think clomonitor is good enough to pilot for another foundation: https://landscape.lfai.foundation

We could just create another instance, lfai.clomonitor.io etc and keep things separate, or find a way to have it all integrated into one UI... I think I prefer the former as it's easier for people to run their own instances down the road imho.

**Comment by tegioz** [comment]
Hi @caniszczyk 👋 

We've just added support for multiple foundations in a single clomonitor instance. It was easier to launch a new instance, but we thought it'd increase costs and maintenance time. You can give it a try and if it doesn't feel right we can switch to something else, it's not a problem.

There is a Helm chart in the repo (not yet in Artifact Hub! 😅) that makes it quite easy to deploy a new clomonitor instance, so it shouldn't be a problem for people to run their own. Please note that there are some hardcoded elements at the moment that are specific to the CNCF (or other LF foundations), like the project maturity or the accepted date. Maybe eventually we could review some of them to make clomonitor more generic and reusable in other contexts.

There is a new filter for foundations and the foundation the project is associated to is now displayed in several places across the UI. You can also view stats per foundation or across all foundations.

<img width="1469" alt="1" src="https://user-images.githubusercontent.com/1213902/162326380-8f3fd064-5acb-491f-a9f3-47542d010023.png">

<img width="1469" alt="2" src="https://user-images.githubusercontent.com/1213902/162326397-8fc7e733-f3ae-46c2-a030-487d6698fedb.png">

**Comment by caniszczyk** [comment]
@tegioz AWESOME, the challenge here will be that not every foundation has the same maturity levels so we will have to be diligent on how we support that, some may just have "incbuation" or "graduated" or have completely different terminology like "At Large" e.g., https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md#iii-stages---definitions--expectations
