### ISSUE TITLE
Ensure stats page can filter by "foundation"

### ISSUE THREAD

**Issue by caniszczyk** [cncf/clomonitor#245]
I want to ensure we can filter by foundation here: https://clomonitor.io/stats

**Comment by tegioz** [comment]
Hi @caniszczyk 👋 

That's already done, please see screenshot below 🙂 

The url will get updated based on the selection, so it's easy to share any foundation's stats as well:

<https://clomonitor.io/stats?foundation=cncf>
<https://clomonitor.io/stats?foundation=lfaidata>

<img width="1491" alt="Screen Shot 2022-04-19 at 19 54 36" src="https://user-images.githubusercontent.com/1213902/164065901-1872ab47-cde4-4483-80ba-6bbd92a9c941.png">
