### ISSUE TITLE
Update cloudevents description

### ISSUE THREAD

**Issue by duglin** [cncf/clomonitor#256]
Right now it says: A specification for describing event data in a common.
It's missing "way" at the end.
Can we get that updated?
Also, we're not part of "App Definition" can we get that fixed too? We're part of the "Serverless WG".

**Comment by tegioz** [comment]
Sure, we'll update the description, no problem 👍 

Regarding the category, we [got it from the CNCF landscape](https://landscape.cncf.io/?project=incubating&selected=cloud-events). We can update that too, just wanted to double check.

**Comment by duglin** [comment]
hmmm the icon only appears under Streaming and Messaging. I guess if we can have others listed (like App Def) can we add "Serverless" too?

**Comment by tegioz** [comment]
I think Streaming and Messaging is the subcategory.

<img width="1383" alt="1" src="https://user-images.githubusercontent.com/1213902/165584603-9ff8f80e-4567-4b1d-bebe-2254ce8f2a42.png">

<img width="1383" alt="2" src="https://user-images.githubusercontent.com/1213902/165584618-c4c2e230-bd8e-4a05-9e55-24e61767e7a0.png">

At the moment we can have only one, up to you 🙂

**Comment by duglin** [comment]
Ah ok - I missed that sidebar thingy... let's just let it remain as it then.

**Comment by duglin** [comment]
Well, except for the missing "way" :-)
