### ISSUE TITLE
Add check for artifact being published on artifacthub

### ISSUE THREAD

**Issue by caniszczyk** [cncf/clomonitor#37]
e.g., https://artifacthub.io/packages/helm/prometheus-community/prometheus

We need to find a way to check for this, one idea is to have maintainers put this data in landscape.yml

**Comment by tegioz** [comment]
What do you think about having a `CloMonitor` metadata file (`.clomonitor.yaml` maybe?) that projects could add to their repositories? In this particular case, they could list the urls of the artifacts they are publishing to Artifact Hub, for example. 

I'm thinking that this could be useful for more items that don't have a concrete way to be checked or items/metadata that are specific to CloMonitor. Maybe it can be of help for SBOMs, or we could even have a section to properly define the public meeting minutes in a structured way: url, when, etc. Plenty of potential use cases 🙂 

Related to #31 , #33, #36

**Comment by tegioz** [comment]
We are implementing this by checking the Artifact Hub badge on the README file (many projects are already using it), but we'll keep in mind the metadata file idea as we think it'll be helpful soon.
