### ISSUE TITLE
Feature request: Filter projects by missing info/data

### ISSUE THREAD

**Issue by nate-double-u** [cncf/clomonitor#404]
Hi -- is there a way to filter projects by missing info/data?

For example, I'd like to see a list of all the CNCF projects that don't yet have a website, is there a way to filter or search for that?

_Originally posted by @nate-double-u in https://github.com/cncf/clomonitor/discussions/391_

**Comment by tegioz** [comment]
I've seen a link in the discussion to covert, but honestly I've never tried it before, not sure what it does.

<img width="255" alt="Screen Shot 2022-06-22 at 15 15 08" src="https://user-images.githubusercontent.com/1213902/175038192-3821ef27-cc13-4c7f-9cec-eb38c9955085.png">

**Comment by nate-double-u** [comment]
I saw that -- recreated the issue using that tool to see what it would do. Mostly there's a formatting difference, and it added a 'created from discussion' link
