### ISSUE TITLE
filter/search for missing data

### ISSUE THREAD

**Issue by nate-double-u** [cncf/clomonitor#405]
### Discussed in https://github.com/cncf/clomonitor/discussions/391

<div type='discussions-op-text'>

<sup>Originally posted by **nate-double-u** June 17, 2022</sup>
Hi -- is there a way to filter projects by missing info/data?

For example, I'd like to see a list of all the CNCF projects that don't yet have a website, is there a way to filter or search for that?</div>

**Comment by tegioz** [comment]
Following up with @jeefy 's [request](https://github.com/cncf/clomonitor/discussions/391#discussioncomment-2994999):

#403 has just been deployed! Hopefully it'll do the trick temporarily 😇 

<https://clomonitor.io/data/repositories.csv>

**Comment by tegioz** [comment]
Deployed!

<img width="1411" alt="checks_filters" src="https://user-images.githubusercontent.com/1213902/179564201-1fc36042-caba-4839-90be-91ffeee91440.png">

**Comment by nate-double-u** [comment]
This is awesome! Thanks so much :D

**Comment by chalin** [comment]
Woohoo! Thanks! 🎉
