### ISSUE TITLE
CNCF project Notary: website not listed

### ISSUE THREAD

**Issue by nate-double-u** [cncf/clomonitor#454]
https://clomonitor.io/projects/cncf/notary/notary

Notary project listed as not having a website.

Notary Project website: https://notaryproject.dev/
Website repo: https://github.com/notaryproject/notaryproject.dev

**Comment by tegioz** [comment]
Hi @nate-double-u 👋

The *website* check is part of the `community` check set, which for this project is run on the `notary` repository (you can see both code and community check sets assigned to that repo).

But the notary repository doesn't have a website defined in GitHub yet. As soon as it's done the check should pass :)

**Comment by tegioz** [comment]
Will close this one for now as there isn't anything to do on the clomonitor side, feel free to reopen if needed.

Please let us know if the check doesn't pass once the website is added to the `notary` repository in GitHub.
