### ISSUE TITLE
Something wrong with the styling

### ISSUE THREAD

**Issue by chalin** [cncf/clomonitor#506]
When I visit https://clomonitor.io, this is what I see (after it automatically redirects to search page 1):

> <img width="1021" alt="image" src="https://user-images.githubusercontent.com/4140793/182954432-3fc2d1c4-882e-43bb-a77a-941951a39bbe.png">

Something seems off. Also, selecting checkboxes doesn't seem to work -- they don't stay checked.

I'm using Chrome (macOS):

- Version 103.0.5060.134 (Official Build) (arm64)
- Version 104.0.5112.79 (Official Build) (arm64)

/cc @nate-double-u

**Comment by tegioz** [comment]
Mmm this may be related to the automatic theme mode feature we added recently in #490.

Could you please try opening it in an incognito window and tell us if you see the same effect @chalin ?

**Comment by chalin** [comment]
In a normal window I did an "Empty cache and hard reset". That did nothing.
The styling is **back to normal when visiting from an incognito window**.

**Comment by tegioz** [comment]
That makes sense, thanks. We've been able to reproduce it, it'll be fixed soon.

In the meantime, as a temporary fix, you can delete the CLOMonitor preferences from the local storage (there should be two entries, you can delete both).

Thanks for reporting this!

**Comment by tegioz** [comment]
Fix deployed!
