### ISSUE TITLE
Token permissions not updated

### ISSUE THREAD

**Issue by jkowall** [cncf/clomonitor#636]
Hello, I would like to understand why the token permissions are not updated : https://clomonitor.io/projects/cncf/jaeger#jaeger_security

We have updated the settings per this issue: https://github.com/jaegertracing/jaeger/issues/3951 

Thanks!

**Comment by tegioz** [comment]
Hi @jkowall 👋 

CLOMonitor uses [Scorecard](https://github.com/ossf/scorecard) for this check. According to [their docs](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions):

> The check cannot detect if the "read-only" GitHub permission setting is enabled, as there is no API available

So to pass this check I think the permissions definitions will need to be set explicitly in the workflow's yaml file.

**Comment by jkowall** [comment]
Thanks!
