### ISSUE TITLE
License scanning and artifact hub badge not updated=

### ISSUE THREAD

**Issue by jkowall** [cncf/clomonitor#637]
We just added license scanning and artifact hub badges into Jaeger : https://github.com/jaegertracing/jaeger/blob/main/README.md (see top)

Our page is still showing these as not done : https://clomonitor.io/projects/cncf/jaeger#jaeger_security

I would appreciate your input.

Thanks!

**Comment by tegioz** [comment]
Hi again!

The Artifact Hub check verifies that the badge includes a link to the repository (yours doesn't include the link yet). Just in case it helps, you can get the code for the badge from the AH's control panel.

<img width="805" alt="Screen Shot 2022-10-10 at 16 13 48" src="https://user-images.githubusercontent.com/1213902/194886878-4a426ae8-3af7-4f8a-a81a-b6d3f7733cfc.png">

Regarding the license scan, CLOMonitor is able to detect FOSSA and Snyk links using the regular expressions defined in the [check docs](https://clomonitor.io/docs/topics/checks/#license-scanning). So to make this one pass you need to update the link in the `license scanning` badge.

You can use these (from the Artifact Hub project) as examples:

[![Artifact HUB](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/artifact-hub)](https://artifacthub.io/packages/helm/artifact-hub/artifact-hub)
[![Licenses](https://app.fossa.io/api/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fartifacthub%2Fhub.svg?type=shield)](https://app.fossa.io/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fartifacthub%2Fhub?ref=badge_shield)

**Comment by jkowall** [comment]
Thanks for the clarification
