### ISSUE TITLE
Provide support for using governance repos

### ISSUE THREAD

**Issue by tomkerkhove** [cncf/clomonitor#66]
Provide support for using governance repos instead of only having GOVERNANCE files.

For example; https://github.com/kedacore/governance is where KEDA's governance is at.

**Comment by OrlinVasilev** [comment]
second that! For example Harbor and Contour we have separate repos for community and we keep GOVERNANCE there!

**Comment by OrlinVasilev** [comment]
@tegioz is the same valid for code of conduct ?

**Comment by OrlinVasilev** [comment]
I've opened PR for that will update you once I have it merged :)

**Comment by tegioz** [comment]
Yes, that works too for code of conduct 👍

**Comment by tegioz** [comment]
Hi @OrlinVasilev 

I've seen the PR you referenced has been merged. At the moment the patterns we detect to pass certain checks must be in the headers of the markdown file. Something like this should work:

```markdown
## Governance

Find GOVERNANCE in our [Community repo](https://github.com/projectcontour/community)
```

I'll close this issue for now as we are addressing it with the headers check. Please don't hesitate pinging me if you run into any issue.
