### ISSUE TITLE
Provide support for listing end-users outside of ADOPTERS

### ISSUE THREAD

**Issue by tomkerkhove** [cncf/clomonitor#67]
Provide support for listing end-users outside of ADOPTERS since KEDA lists everybody on https://keda.sh/community/#users

**Comment by tegioz** [comment]
Hi @tomkerkhove 👋 

Could you consider adding an `ADOPTERS.md` file to your repository pointing to that url?

Checking for `.github` or `governance` repositories at the organization level is fine, as they are conventions and we'd know where to look at. But custom projects' urls would require checks to be customizable per project and/or repository. We could do that, but I'm not sure if it's the right way to go. IMHO it's best to rely on standard locations whenever possible as that's where users may start looking at first when searching for some piece of information.

**Comment by tomkerkhove** [comment]
That makes sense.

> Checking for `.github` or `governance` repositories at the organization level is fine, as they are conventions and we'd know where to look at.

Before I go there, are you saying this will or will not be supported?

**Comment by tegioz** [comment]
We have plans to support .github repos, but we can also consider governance ones if it's a common convention.

**Comment by tomkerkhove** [comment]
Great, thank you! We will keep things there then and fill the gaps.

Closing as Adopters is the way to go.
