### ISSUE TITLE
Consider a Makefile for easier development

### ISSUE THREAD

**Issue by jeefy** [cncf/clomonitor#78]
I'd love it if there were a Makefile so I could simply run `make run` or `make serve` off my fork and have a local copy up and running for tinkering. Likewise from there you could have things like `make images` and `make images-push` and whatnot tied together.

**Comment by tegioz** [comment]
Related to #44

**Comment by tegioz** [comment]
It's now possible to spin up a development environment with [a single click by using Gitpod](https://gitpod.io/#https://github.com/cncf/clomonitor) 🙂. We've also added some documentation about the project's [architecture](https://github.com/cncf/clomonitor/blob/main/docs/architecture.md) and [a guide to setup a development environment](https://github.com/cncf/clomonitor/blob/main/docs/dev.md) locally.

I think this pretty much covers the needs for the different contributing scenarios, so maybe we can close this issue.

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
