### ISSUE TITLE
Enable a way for end users to queue a re-check

### ISSUE THREAD

**Issue by jeefy** [cncf/clomonitor#79]
The method for this could be up for debate, but initial thoughts:
- Via the site using GH SSO to see if the person is part of the project's org 
- A webhook that projects could tie a GitHub action into (and then each project be given an API key of sorts) 
- A completely offline check by cloning the clo monitor repo down and running `make run` locally to queue a fresh pull of everything
  - Ninja edit: Another cooler idea would be allowing them to run some sort of command if they clone down this repo. Think:
    ```
    make build
    clomonitor-check kubernetes #established project
    # OR
    clomonitor-check https://github.com/jeefy/tenta # unrelated project
    ```
    And then output a score via the CLI. 
    
    I think the ideal path would be for someone to check their own score without any action from us.

**Comment by tegioz** [comment]
Hi @jeefy 👋 

Please see https://github.com/cncf/clomonitor/discussions/20 🙂

**Comment by jeefy** [comment]
:raised_hands: 
Closing in favor of #20 

I think I'll look in Discussions now lol
