### ISSUE TITLE
"Changes" check fails with changes listed in latest *non-rc* releases

### ISSUE THREAD

**Issue by cwayne18** [cncf/clomonitor#792]
For the k3s dashboard (https://clomonitor.io/projects/cncf/k3s#k3s), the Changelog check is failing, despite the latest releases in Github containing a list of "Changes": https://github.com/k3s-io/k3s/releases/tag/v1.25.4%2Bk3s1

I think the check itself does not take into account RC releases or those that are marked as "pre-release".

**Comment by cwayne18** [comment]
Perhaps https://github.com/cncf/clomonitor/blob/d2d18a46b9894a5fb0e33759f4dc493662c8c061/clomonitor-core/src/linter/checks/util/github/mod.rs#L209 should check if the release `isPrerelease` https://github.com/cncf/clomonitor/blob/ebb901486ae9d0fd93e477615500d0451a1c7500/clomonitor-core/src/linter/checks/util/github/github_schema.graphql#L32615

**Comment by tegioz** [comment]
Thanks for reporting this issue and looking into it @cwayne18!
