### ISSUE TITLE
Adding additional repositories

### ISSUE THREAD

**Issue by xmulligan** [cncf/clomonitor#809]
For the [Cilium project](https://clomonitor.io/projects/cncf/cilium), CLOMonitor currently checks two repos: the [Cilium](https://github.com/cilium/cilium) and [ebpf](https://github.com/cilium/ebpf) ones. Is it possible to add more repos? Specifically, we would like to add [Tetragon](https://github.com/cilium/tetragon).

**Comment by tegioz** [comment]
Hi @xmulligan 👋 

Sure, adding more repos is not a problem. Tetragon is currently [listed on CLOMonitor](https://clomonitor.io/projects/cncf/tetragon) as a separate project actually. But this can be easily fixed if it's not right 😇

Projects are controlled via data files available [here](https://github.com/cncf/clomonitor/tree/main/data). Please feel free to submit a PR if you'd like to make any changes (they'll be picked up by CLOMonitor automatically). Or we can make them for you if you prefer 🙂

**Comment by tegioz** [comment]
BTW [Hubble](https://clomonitor.io/projects/cncf/hubble) is also listed as a different project.

**Comment by xmulligan** [comment]
Ahh thanks, I didn't realize that. I've made #814. Let me know if that is ok 🙂

**Comment by tegioz** [comment]
The new repos are now displayed in the [Cilium's project CLOMonitor page](https://clomonitor.io/projects/cncf/cilium) @xmulligan. Sad to see the coolest icon ever (Tetragon's) leave CLOMonitor! 🥲

**Comment by xmulligan** [comment]
Thanks! I would be happy to add it back if sub projects can have logos too :D
