### ISSUE TITLE
Add check for CNCF Project Summary table

### ISSUE THREAD

**Issue by jeefy** [cncf/clomonitor#995]
The CNCF Business Value Subcommittee has developed a project summary table to supplement the CNCF Landscape and include further information about CNCF projects for the wider cloud native community. It would be awesome if we could have CLOMonitor check if a project has data in the table. 

The table is located here: https://landscape.cncf.io/summary

The directions to add data are located here: https://github.com/cncf/landscape/blob/master/readme_summary.md

cc @RiichardCC

**Comment by tegioz** [comment]
Hi @jeefy 👋 

Quick question: would the check pass if *any*, *some* or *all* of the fields listed below are set for a project?

```
summary_personas
summary_tags
summary_use_case
summary_business_use_case
summary_release_rate
summary_integrations
summary_intro_url
```

**Comment by tegioz** [comment]
Hi @jeefy

This is kind of ready! We'll run some more tests and deploy it tomorrow. We've gone with the *any* option for now, but it can be changed if needed 🙂 We are also displaying the data identified on the UI to make it easier to inspect it.

<img width="822" alt="summary_table" src="https://user-images.githubusercontent.com/1213902/229541488-da4d369a-b794-4390-a36f-ca1e0fcb0775.png">

<img width="1405" alt="summary_table_stats" src="https://user-images.githubusercontent.com/1213902/229541508-1832c29d-2e67-4f58-b672-a9871844c160.png">

**Comment by tegioz** [comment]
Deployed!
